# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tic-tac-toe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import control
from gameboard import Gameboard


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.B0Button = QtWidgets.QPushButton(self.centralwidget)
        self.B0Button.setGeometry(QtCore.QRect(250, 110, 81, 91))
        self.B0Button.setText("")
        self.B0Button.setObjectName("B0Button")
        self.B1Button = QtWidgets.QPushButton(self.centralwidget)
        self.B1Button.setGeometry(QtCore.QRect(350, 110, 81, 91))
        self.B1Button.setText("")
        self.B1Button.setObjectName("B1Button")
        self.B2Button = QtWidgets.QPushButton(self.centralwidget)
        self.B2Button.setGeometry(QtCore.QRect(450, 110, 81, 91))
        self.B2Button.setText("")
        self.B2Button.setObjectName("B2Button")
        self.B3Button = QtWidgets.QPushButton(self.centralwidget)
        self.B3Button.setGeometry(QtCore.QRect(250, 220, 81, 91))
        self.B3Button.setText("")
        self.B3Button.setObjectName("B3Button")
        self.B5Button = QtWidgets.QPushButton(self.centralwidget)
        self.B5Button.setGeometry(QtCore.QRect(450, 220, 81, 91))
        self.B5Button.setText("")
        self.B5Button.setObjectName("B5Button")
        self.B4Button = QtWidgets.QPushButton(self.centralwidget)
        self.B4Button.setGeometry(QtCore.QRect(350, 220, 81, 91))
        self.B4Button.setText("")
        self.B4Button.setObjectName("B4Button")
        self.B6Button = QtWidgets.QPushButton(self.centralwidget)
        self.B6Button.setGeometry(QtCore.QRect(250, 330, 81, 91))
        self.B6Button.setText("")
        self.B6Button.setObjectName("B6Button")
        self.B8Button = QtWidgets.QPushButton(self.centralwidget)
        self.B8Button.setGeometry(QtCore.QRect(450, 330, 81, 91))
        self.B8Button.setText("")
        self.B8Button.setObjectName("B8Button")
        self.B7Button = QtWidgets.QPushButton(self.centralwidget)
        self.B7Button.setGeometry(QtCore.QRect(350, 330, 81, 91))
        self.B7Button.setText("")
        self.B7Button.setObjectName("B7Button")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(360, 40, 61, 16))
        self.TitleLabel.setObjectName("TitleLabel")
        self.P1Textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.P1Textbox.setGeometry(QtCore.QRect(50, 50, 113, 22))
        self.P1Textbox.setObjectName("P1Textbox")
        self.P1Label = QtWidgets.QLabel(self.centralwidget)
        self.P1Label.setGeometry(QtCore.QRect(70, 20, 55, 16))
        self.P1Label.setObjectName("P1Label")
        self.P2Label = QtWidgets.QLabel(self.centralwidget)
        self.P2Label.setGeometry(QtCore.QRect(630, 20, 55, 16))
        self.P2Label.setObjectName("P2Label")
        self.P2Textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.P2Textbox.setGeometry(QtCore.QRect(610, 50, 113, 22))
        self.P2Textbox.setObjectName("P2Textbox")
        self.SRButton = QtWidgets.QPushButton(self.centralwidget)
        self.SRButton.setGeometry(QtCore.QRect(340, 460, 93, 28))
        self.SRButton.setObjectName("SRButton")
        self.RoundNum = QtWidgets.QLabel(self.centralwidget)
        self.RoundNum.setGeometry(QtCore.QRect(20, 510, 55, 16))
        self.RoundNum.setObjectName("RoundNum")
        self.P1Score = QtWidgets.QLabel(self.centralwidget)
        self.P1Score.setGeometry(QtCore.QRect(90, 100, 55, 16))
        self.P1Score.setObjectName("P1Score")
        self.P2Score = QtWidgets.QLabel(self.centralwidget)
        self.P2Score.setGeometry(QtCore.QRect(650, 100, 55, 16))
        self.P2Score.setObjectName("P2Score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SRButton.clicked.connect(lambda:control.start(self))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic-tac-toe"))
        self.TitleLabel.setText(_translate("MainWindow", "Tic-tac-toe"))
        self.P1Label.setText(_translate("MainWindow", "Player 1"))
        self.P2Label.setText(_translate("MainWindow", "Player 2"))
        self.SRButton.setText(_translate("MainWindow", "Start"))
        self.RoundNum.setText(_translate("MainWindow", "Round: 1"))
        self.P1Score.setText(_translate("MainWindow", "0 pts"))
        self.P2Score.setText(_translate("MainWindow", "0 pts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
